from __future__ import annotations

import os
import re
import sys
import time
import subprocess
from pathlib import Path

ROOT = Path(__file__).parent
ENV_PATH = ROOT / ".env"
ENV_EXAMPLE_PATH = ROOT / ".env.example"
CHARACTER_CARDS_DIR = ROOT / "character_cards"


# ─────────────────────── 基础工具函数 ───────────────────────


def _load_existing_env() -> dict[str, str]:
    env = {}
    if ENV_PATH.exists():
        with open(ENV_PATH, "r", encoding="utf-8") as f:
            for line in f:
                stripped = line.strip()
                if not stripped or stripped.startswith("#"):
                    continue
                if "=" in stripped:
                    k, v = stripped.split("=", 1)
                    env[k.strip()] = v.strip()
    return env


def _env_write(key: str, value: str) -> None:
    lines: list[str] = []
    found = False
    if ENV_PATH.exists():
        with open(ENV_PATH, "r", encoding="utf-8") as f:
            for line in f:
                stripped = line.lstrip()
                if stripped.startswith("#") or stripped == "":
                    lines.append(line)
                    continue
                if "=" in stripped:
                    k = stripped.split("=", 1)[0].strip()
                    if k.upper() == key.upper():
                        lines.append(f"{key}={value}\n")
                        found = True
                        continue
                lines.append(line)
    else:
        lines.append("# DSN-exp .env (auto-generated by onboarding)\n")
    if not found:
        lines.append(f"{key}={value}\n")
    with open(ENV_PATH, "w", encoding="utf-8") as f:
        f.writelines(lines)


def _env_read(key: str) -> str:
    env = _load_existing_env()
    return env.get(key, env.get(key.upper(), ""))


def _is_configured() -> bool:
    if not ENV_PATH.exists():
        return False
    env = _load_existing_env()
    key = env.get("DEEPSEEK_API_KEY", "")
    return bool(key and key != "sk-your-key-here")


def _run_shell(cmd: str, timeout: int = 30) -> dict:
    try:
        result = subprocess.run(
            cmd, shell=True, capture_output=True, text=True, timeout=timeout,
            cwd=str(ROOT),
        )
        return {
            "success": result.returncode == 0,
            "output": result.stdout.strip(),
            "error": result.stderr.strip(),
            "exit_code": result.returncode,
        }
    except subprocess.TimeoutExpired:
        return {"success": False, "output": "", "error": "命令超时", "exit_code": -1}
    except Exception as e:
        return {"success": False, "output": "", "error": str(e), "exit_code": -1}


def _run_python(code: str, timeout: int = 30) -> dict:
    import tempfile
    tmp = tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False, encoding="utf-8")
    try:
        tmp.write(code)
        tmp.close()
        result = _run_shell(f'"{sys.executable}" "{tmp.name}"', timeout=timeout)
        return result
    finally:
        try:
            os.unlink(tmp.name)
        except Exception:
            pass


def _create_chat(api_key: str):
    from models.clients import DeepSeekChat
    return DeepSeekChat(api_key=api_key)


def _chat_send_with_retry(chat, message: str, max_retries: int = 3) -> str | None:
    """发送消息，网络错误时自动重试。重试耗尽后询问用户是否继续。"""
    retries = 0
    while True:
        try:
            return chat.send_message(message)
        except Exception as e:
            retries += 1
            if retries <= max_retries:
                wait = min(2 ** retries, 10)
                print(f"  ⚠ 网络请求失败 (第 {retries}/{max_retries} 次重试): {e}")
                print(f"    等待 {wait} 秒后重试...")
                try:
                    time.sleep(wait)
                except KeyboardInterrupt:
                    print("\n  已取消。")
                    return None
            else:
                print(f"  ⚠ 网络请求失败，已重试 {max_retries} 次: {e}")
                choice = _safe_input("  是否继续重试? (Y/n): ").lower()
                if choice in ("", "y", "yes"):
                    retries = 0
                else:
                    return None


def _render_markdown(text: str) -> None:
    try:
        from rich.console import Console
        from rich.markdown import Markdown
        console = Console()
        console.print(Markdown(text))
    except ImportError:
        print(text)


def _safe_input(prompt: str = "") -> str:
    try:
        return input(prompt).strip()
    except EOFError:
        return ""
    except UnicodeDecodeError:
        return ""


# ─────────────────────── 环境检测（静默采集） ───────────────────────


def _check_python() -> dict:
    ver = sys.version_info
    return {
        "version": f"{ver.major}.{ver.minor}.{ver.micro}",
        "executable": sys.executable,
        "ok": ver >= (3, 10),
    }


def _check_conda() -> dict:
    r = _run_shell("conda --version 2>/dev/null || echo NOT_FOUND")
    if "NOT_FOUND" in r["output"]:
        return {"available": False, "version": ""}
    return {"available": True, "version": r["output"].strip()}


def _check_pip_packages() -> dict:
    import importlib.metadata

    req_path = ROOT / "requirements.txt"
    if not req_path.exists():
        return {"all_ok": True, "missing": [], "errors": []}

    required = {}
    with open(req_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            m = re.match(r"^([A-Za-z0-9_\-]+)", line)
            if m:
                required[m.group(1).lower()] = line

    missing = []
    errors = []
    for pkg_name, req_line in required.items():
        try:
            importlib.metadata.version(pkg_name)
        except importlib.metadata.PackageNotFoundError:
            missing.append(req_line)
        except Exception as e:
            errors.append(f"{pkg_name}: {e}")

    return {"all_ok": len(missing) == 0 and len(errors) == 0, "missing": missing, "errors": errors}


def _check_third_party() -> dict:
    result = {}

    r = _run_shell(
        "curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:9880 2>/dev/null || echo 000",
        timeout=5,
    )
    tts_running = r["output"].strip() == "200"
    if not tts_running:
        for _i in range(2):
            time.sleep(2)
            r = _run_shell(
                "curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:9880 2>/dev/null || echo 000",
                timeout=5,
            )
            if r["output"].strip() == "200":
                tts_running = True
                break
    result["tts"] = {
        "name": "GPT-SoVITS (TTS 语音合成, 端口 9880)",
        "running": tts_running,
    }

    r = _run_shell(
        "curl -s -o /dev/null -w '%{http_code}' http://localhost:8000 2>/dev/null || echo 000",
        timeout=5,
    )
    result["2md"] = {
        "name": "2md (文档解析服务, 端口 8000)",
        "running": r["output"].strip() == "200",
    }

    r = _run_shell(
        "curl -s -o /dev/null -w '%{http_code}' http://localhost:4501/v1/models 2>/dev/null || echo 000",
        timeout=5,
    )
    lm_running = r["output"].strip() == "200"
    if not lm_running:
        for _i in range(2):
            time.sleep(2)
            r = _run_shell(
                "curl -s -o /dev/null -w '%{http_code}' http://localhost:4501/v1/models 2>/dev/null || echo 000",
                timeout=5,
            )
            if r["output"].strip() == "200":
                lm_running = True
                break
    result["lmstudio"] = {
        "name": "LMStudio (本地模型推理, 端口 4501)",
        "running": lm_running,
    }

    return result


def _collect_environment_info() -> dict:
    """静默采集环境信息，不做任何打印，返回采集结果供 AI 使用。"""
    env_info: dict = {}

    py = _check_python()
    env_info["python"] = py

    conda = _check_conda()
    env_info["conda"] = conda

    pkgs = _check_pip_packages()
    env_info["packages"] = pkgs

    third = _check_third_party()
    env_info["services"] = third

    return {"success": py["ok"], "env_info": env_info}


def _install_missing_packages(env_info: dict) -> None:
    """如有缺失依赖则询问用户并安装。"""
    pkgs = env_info.get("packages", {})
    if not pkgs.get("missing"):
        return

    print(f"\n  缺少 {len(pkgs['missing'])} 个依赖包:")
    for m in pkgs["missing"][:5]:
        print(f"    - {m}")
    if len(pkgs["missing"]) > 5:
        print(f"    ... 还有 {len(pkgs['missing']) - 5} 个")

    install = _safe_input("\n  是否安装缺失依赖? (Y/n): ").lower()
    if install in ("", "y", "yes"):
        print("  正在安装...")
        r = _run_shell(
            f'"{sys.executable}" -m pip install -r "{ROOT / "requirements.txt"}"',
            timeout=300,
        )
        if r["success"]:
            print("  ✓ 安装完成")
        else:
            print(f"  安装失败: {r['error'][:100]}")
            print("  请手动运行: pip install -r requirements.txt")


# ─────────────────────── 配置信息读取 ───────────────────────


def _get_env_config_info() -> str:
    """读取 .env.example 内容供 AI 参考。"""
    if ENV_EXAMPLE_PATH.exists():
        return ENV_EXAMPLE_PATH.read_text(encoding="utf-8")
    return "(无 .env.example 文件)"


def _get_current_config() -> str:
    """获取当前已配置的内容摘要。"""
    env = _load_existing_env()
    configured = []
    for k, v in env.items():
        if v and v != "sk-your-key-here":
            display_v = v[:20] + "..." if len(v) > 20 else v
            configured.append(f"- {k}={display_v}")
    if configured:
        return "已配置的内容:\n" + "\n".join(configured)
    return "当前没有已配置的内容"


def _get_character_cards_info() -> str:
    """获取可用角色卡列表。"""
    if not CHARACTER_CARDS_DIR.exists():
        return "没有预设角色卡"
    cards = []
    for f in CHARACTER_CARDS_DIR.glob("*.yaml"):
        cards.append(f.stem)
    for f in CHARACTER_CARDS_DIR.glob("*.json"):
        cards.append(f.stem)
    if cards:
        return "可用角色卡: " + ", ".join(cards)
    return "没有预设角色卡"


# ─────────────────────── 角色卡创建 ───────────────────────


def _create_character_card(name: str, personality: str, speech_style: str) -> str:
    """根据 AI 传回的参数创建自定义角色卡 YAML 文件，返回 card_id。"""
    safe_name = re.sub(r'[^\w\-]', '_', name.lower())
    card_id = f"custom_{safe_name}"
    card_path = CHARACTER_CARDS_DIR / f"{card_id}.yaml"
    CHARACTER_CARDS_DIR.mkdir(parents=True, exist_ok=True)

    yaml_content = f"""card_id: {card_id}
name: {name}
display_name: {name}
version: '1.0'
description: 用户自定义角色
author: user
extends: ''
natural_language:
  personality: >
    {personality}
  speech_style: >
    {speech_style}
corpus: []
experiences: []
dynamic_config:
  seed: 42
  noise_amplitude: 0.12
  mood_volatility: 0.15
  temporal_drift_rate: 0.02
  response_inertia: 0.35
  environment_sensitivity: 0.25
manual_overrides: {{}}
"""
    card_path.write_text(yaml_content, encoding="utf-8")
    return card_id


# ─────────────────────── API Key 获取 ───────────────────────


def _get_api_key() -> str | None:
    """获取 DeepSeek API Key（此步骤发生在 AI 就绪之前，只能手动输入）。"""
    existing = _env_read("DEEPSEEK_API_KEY")
    api_key = None

    if existing and existing != "sk-your-key-here":
        print(f"\n  已检测到 API Key: {existing[:8]}...{existing[-4:]}")
        confirm = _safe_input("  使用此 Key? (Y/n): ").lower()
        if confirm in ("", "y", "yes"):
            api_key = existing

    if not api_key:
        print("\n  [配置 DeepSeek API Key]")
        print("  获取地址: https://platform.deepseek.com\n")

        while True:
            key = _safe_input("  请输入 API Key (sk-...): ")

            if key.lower() == "/quit":
                return None

            if not key:
                print("  请输入有效的 API Key")
                continue

            if not key.startswith("sk-"):
                print("  API Key 通常以 'sk-' 开头，请确认是否正确")
                confirm = _safe_input("  继续使用此 Key? (y/N): ").lower()
                if confirm != "y":
                    continue

            print("  验证中...")
            _env_write("DEEPSEEK_API_KEY", key)
            from dotenv import load_dotenv
            load_dotenv(ENV_PATH, override=True)

            try:
                chat = _create_chat(key)
                chat.messages = [{"role": "system", "content": "请回复 OK。"}]
                test_reply = chat.send_message("ping")
                if test_reply:
                    print("  ✓ API Key 验证成功")
                    api_key = key
                    break
            except Exception as e:
                print(f"  验证失败: {e}")
                retry = _safe_input("  重新输入? (Y/n): ").lower()
                if retry in ("n", "no"):
                    return None
                continue

    return api_key


# ─────────────────────── AI 引导配置主流程 ───────────────────────


def _ai_guided_configure(api_key: str, env_info: dict) -> bool:
    """AI 通过自然语言对话引导用户完成全部配置（角色卡 + .env 功能）。"""
    chat = _create_chat(api_key)

    env_example_content = _get_env_config_info()
    current_config = _get_current_config()
    cards_info = _get_character_cards_info()

    # 将环境检测结果整理为文本摘要
    env_summary = (
        f"Python {env_info['python']['version']} "
        f"({'OK' if env_info['python']['ok'] else '需要升级'}), "
        f"Conda {'已安装 ' + env_info['conda']['version'] if env_info['conda']['available'] else '未安装'}, "
        f"依赖包 {'全部安装' if env_info['packages']['all_ok'] else f'缺少 {len(env_info["packages"]["missing"])} 个'}, "
        f"TTS {'运行中' if env_info['services']['tts']['running'] else '未运行'}, "
        f"文档解析 {'运行中' if env_info['services']['2md']['running'] else '未运行'}, "
        f"LMStudio {'运行中' if env_info['services']['lmstudio']['running'] else '未运行'}"
    )

    system_prompt = f"""你是 DSN-exp 系统的配置向导，通过自然语言对话帮助用户完成所有配置。

当前状态：
- DEEPSEEK_API_KEY 已配置好，无需再配置
- 环境检测：{env_summary}
- {cards_info}

你的任务分两大步，必须按顺序完成：

**第一步：角色卡配置**
先向用户问好并简要介绍环境状态，然后询问用户想如何配置 AI 角色：
1. 使用默认角色卡 (EXA)
2. 创建自定义角色卡
3. 跳过，以后再配置

如果用户选择创建自定义角色卡，通过多轮自然对话收集角色的名字、性格特点和说话方式。
收集完成后，在回复中输出以下格式来触发创建（每项一行，值写在同一行）：

[CREATE_CARD]
name: 角色名
personality: 性格描述（一句话概括即可）
speech_style: 说话方式（一句话概括即可）
[/CREATE_CARD]

如果用户选择使用默认角色卡或跳过，则直接进入第二步。

**第二步：系统功能配置**
根据 .env.example 中的功能分组，逐个询问用户是否需要配置。

.env.example 完整内容：
```
{env_example_content}
```

{current_config}

对每个功能组：
- 用一两句话简要介绍该功能的用途
- 询问用户是否启用以及需要什么配置值
- 如果用户说"默认"/"跳过"/"不需要"/"不"，则跳过该功能组
- 如果用户提供了具体的配置值，在回复中使用 [CONFIG]KEY=VALUE[/CONFIG] 格式
- 一次可以写入多个配置项

对话规则：
- 每次只介绍并询问一个功能组，不要一次性列出所有配置让用户回答
- 语气友好、自然、轻松
- 使用 markdown 格式让回复更清晰
- 如果用户想回头修改之前的配置，灵活处理
- 所有配置完成后，用一句话总结已配置的内容，然后输出 [CONFIG_COMPLETE] 标签
"""

    chat.messages = [{"role": "system", "content": system_prompt}]
    reply = _chat_send_with_retry(
        chat,
        "请开始引导用户完成配置。先问好，简要介绍环境状态，然后开始第一步角色卡配置。"
    )
    if reply is None:
        print("  配置已取消（网络不可用）。")
        return False
    os.system('cls' if os.name == 'nt' else 'clear')
    _render_markdown(reply)

    max_turns = 50
    for _ in range(max_turns):
        user_input = _safe_input("\n你: ")
        if not user_input:
            continue
        if user_input.lower() in ("/quit", "/exit", "退出"):
            print("  配置已取消。")
            return False

        chat.messages.append({"role": "assistant", "content": reply})
        chat.messages.append({"role": "user", "content": user_input})

        response = _chat_send_with_retry(
            chat,
            f"用户说: {user_input}\n\n"
            "如果需要创建角色卡，使用 [CREATE_CARD]...[/CREATE_CARD] 格式。\n"
            "如果需要写入配置，使用 [CONFIG]KEY=VALUE[/CONFIG] 格式。\n"
            "如果所有配置已完成，输出 [CONFIG_COMPLETE] 标签。\n"
            "如果不需要操作，直接正常回复即可。"
        )
        if response is None:
            print("  配置已取消（网络不可用）。")
            return False

        # ── 处理角色卡创建指令 ──
        card_match = re.search(
            r'\[CREATE_CARD\](.+?)\[/CREATE_CARD\]', response, re.DOTALL
        )
        if card_match:
            block = card_match.group(1).strip()
            card_data: dict[str, str] = {}
            current_key = None
            for line in block.split('\n'):
                kv = re.match(r'^(\w+):\s*(.*)', line)
                if kv:
                    current_key = kv.group(1).strip()
                    card_data[current_key] = kv.group(2).strip()
                elif current_key and line.strip():
                    card_data[current_key] += ' ' + line.strip()

            card_name = card_data.get('name', '')
            if card_name:
                card_id = _create_character_card(
                    card_name,
                    card_data.get('personality', f'{card_name} 是一个友好的 AI 助手'),
                    card_data.get('speech_style', f'{card_name} 说话简洁明了'),
                )
                print(f"  ✓ 角色卡已创建: {card_id}")
            else:
                print("  ⚠ 角色卡创建失败：未解析到角色名称")

        # ── 处理配置写入指令 ──
        config_matches = re.findall(r'\[CONFIG\](.+?)\[/CONFIG\]', response)
        for match in config_matches:
            if "=" in match:
                key, value = match.split("=", 1)
                key, value = key.strip(), value.strip()
                _env_write(key, value)
                display_v = value[:20] + "..." if len(value) > 20 else value
                print(f"  ✓ 已配置: {key}={display_v}")

        # ── 清理标签后显示给用户 ──
        display = re.sub(
            r'\[CREATE_CARD\].*?\[/CREATE_CARD\]', '', response, flags=re.DOTALL
        )
        display = re.sub(r'\[CONFIG\].*?\[/CONFIG\]', '', display)
        display = re.sub(r'\[CONFIG_COMPLETE\]', '', display).strip()

        if display:
            os.system('cls' if os.name == 'nt' else 'clear')
            _render_markdown(display)
            reply = display
        else:
            reply = response

        # ── 判断是否完成 ──
        if "[CONFIG_COMPLETE]" in response:
            return True

    return True


# ─────────────────────── 主入口 ───────────────────────


def run() -> bool:
    """运行完整的引导流程。返回 True 表示配置完成。"""
    try:
        print("""
  DSN-exp 首次启动 — 配置引导
""")
        print("  输入 /quit 随时退出\n")

        # ── 静默采集环境信息 ──
        env_result = _collect_environment_info()
        if not env_result["success"]:
            print("  需要 Python 3.10+，请升级后重试。")
            return False

        # ── 处理缺失依赖 ──
        _install_missing_packages(env_result["env_info"])

        # ── API Key 获取（AI 尚未就绪，只能手动输入） ──
        api_key = _get_api_key()
        if not api_key:
            return False

        # ── AI 引导的完整配置（角色卡 + 全部功能配置） ──
        print("\n" + "=" * 50)
        print("  接下来由 AI 引导你完成所有配置")
        print("=" * 50 + "\n")

        _ai_guided_configure(api_key, env_result["env_info"])

        print("""
  配置完成！

  现在重新运行 main.py 即可启动完整系统：
    python main.py

  你也可以随时运行以下命令重新配置：
    python onboarding.py
""")
        return True
    except KeyboardInterrupt:
        print("\n  引导已取消。")
        return False


if __name__ == "__main__":
    success = run()
    sys.exit(0 if success else 1)
